# Generated by Django 4.0 on 2021-12-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylawyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='cost',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='rating',
            field=models.CharField(max_length=6),
        ),
    ]
