# Generated by Django 4.0 on 2021-12-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratemylawyer', '0008_comment_approved_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='lawyer_id',
            new_name='post',
        ),
    ]
